name: ci

on: [push, pull_request]

jobs:
  ci-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
      - name: SCM
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Install backend
      - run: CI=true npm install -g ganache-cli truffle web3@1.6.0
      - run: ganache-cli -p 8545 > /dev/null &
      - run: CI=true npm  install
      # Fixing  problem on Node v14.15.3 by installing pify
      - run: npm install --save-dev pify
      #- run: truffle test
      # This one will produce all required artifacts in "client/src/contract" directory.
      # and will be used latter in the "ci-fronted" section when we also testing fronted build.
      - run: truffle migrate --network development --reset
      
  ci-fronted:
    runs-on: ubuntu-latest
    # Triggered only ci-fronted was success
    needs: ci-backend
    defaults:
      run:
        working-directory: client/     
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
      - name: SCM
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Install and test Fronted
      - run: CI=true npm  install
      # - run: npm run build --if-present
      - run: CI=true npm test --coverage --watchAll